### ISSUE TITLE
All reading lists unexpectedly reset back to previous day

### ISSUE THREAD

**Issue by dizzib** [unquenchedservant/Unquenched-Bible#27]
This morning on 12 December when offline, I marked 5 reading lists as done, down the left side from the Gospels (Matthew 9) to the Prophets (Ezekiel 32). Then a few hours later when back online, I marked the Pentateuch (Leviticus 26) as done.

The app immediately reset all reading lists back a day, as if it were the start of 11 December, with the Pentateuch showing as Leviticus 25, etc...

![Screenshot_20201212-173826](https://user-images.githubusercontent.com/1223150/101991060-1cc56880-3ca2-11eb-80f9-8591b653df25.png)

Nothing is advancing anymore, and the lists down the left cannot be marked as done.

I seem to remember opening the app on another device today, and I suspect this issue has something to do with syncing across devices.

**Comment by unquenchedservant** [comment]
Most likely has to do with syncing across devices. Il take a look though. 

Are you able to mark them as done if you fully close the app and reopen?

**Comment by dizzib** [comment]
After closing then reopening the app I was still unable to advance any list individually, they were still all stuck on the previous day. 

However clicking "mark all done" worked, then I was able to manually force a daily reset :)

**Comment by unquenchedservant** [comment]
Huh, that is interesting. I'll take a look into it, thank you.

**Comment by unquenchedservant** [comment]
Closed with #85
