### ISSUE TITLE
"Titus Finished!" appears several times prematurely

### ISSUE THREAD

**Issue by dizzib** [unquenchedservant/Unquenched-Bible#75]
After finishing Titus 2 the following dialog appeared a few times, with several seconds between each appearance, even before Titus 3 is finished...

![Screenshot_20210211-101553](https://user-images.githubusercontent.com/1223150/107625191-dbc2e380-6c53-11eb-9852-225a6ee37bbe.png)

Would it be possible to have an option to disable such dialogs completely, to save having to click after finishing a book? Thanks! :)

Android app v2.0.3

**Comment by unquenchedservant** [comment]
I will be pushing out an update in just a moment that disables the alert entirely until I can get it working properly. When I reenable it, I'll add an option in settings to enable or disable it.
