### ISSUE TITLE
PGH daily reading list does not advance

### ISSUE THREAD

**Issue by dizzib** [unquenchedservant/Unquenched-Bible#87]
Since upgrading to 2.1.1 the daily reading list does not advance for the Grant Horner system. So every day I first have to mark all done and force a daily reset, to get the list to where it should be.

**Comment by unquenchedservant** [comment]
Just now seeing this. That is a big issue, yes.

**Comment by unquenchedservant** [comment]
I believe I've solved this issue. Should be coming in an update within the next day or so, and a connected commit shortly.

**Comment by unquenchedservant** [comment]
by in the next day or so i meant a week later :P

**Comment by dizzib** [comment]
Fixed in 2.2.0. Thanks! 😀
