### ISSUE TITLE
unreadable dark-on-dark color

### ISSUE THREAD

**Issue by uniqueid001** [unquenchedservant/Unquenched-Bible#89]
![Screenshot_20210720-212208~2](https://user-images.githubusercontent.com/12715614/126416478-7c9838f8-759a-47a3-bca6-c073a69dc6ca.png)

This is Android 8.1 on a Moto G5 Plus;
I see the same appearance on Android 11 on a Moto g power.

**Comment by unquenchedservant** [comment]
This problem is now resolved. Domain expired. Give it an hour or so if you're still experiencing the issue.
